# FROM node:18-alpine

# # Habilitar pnpm
# RUN corepack enable && corepack prepare pnpm@latest --activate

# # Establecer directorio de trabajo
# WORKDIR /app

# # Copiar archivos de dependencia
# COPY package.json pnpm-lock.yaml ./

# # Instalar dependencias
# RUN pnpm install

# # Copiar el resto del proyecto
# COPY . .

# # Exponer puerto
# EXPOSE 3000

# # Comando de desarrollo
# CMD ["pnpm", "dev"]
